Greeting.create(message: 'salut combi!')
Greeting.create(message: 'Yooo na haa ehh!')
Greeting.create(message: 'xa dit quoi boss!')
Greeting.create(message: 'Bonjour!')
Greeting.create(message: 'aww mon petit')
